# Generated by Django 5.2 on 2025-05-05 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=33, null=True)),
                ('action', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('watch', 'Watch'), ('report', 'Report')], default='watch', max_length=20)),
                ('extra_info', models.TextField(blank=True, null=True)),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('remote_ip', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
