video_languages = (
    ("ar", "Arabic"),
    ("ba", "Bangla"),
    ("be", "Bengali"),
    ("my", "Burmese"),
    ("km", "Cambodian"),
    ("ca", "Cantonese"),
    ("ce", "Cebuano"),
    ("ch", "Chammoro"),
    ("dh", "Dhivehi"),
    ("dz", "Dzongkha"),
    ("en", "English"),
    ("fi", "Fijian"),
    ("fr", "French"),
    ("de", "German"),
    ("ha", "Halia"),
    ("hi", "Hindi"),
    ("ind", "Indonesian"),
    ("it", "Italian"),
    ("ja", "Japanese"),
    ("jw", "Javanese"),
    ("ka", "Karen"),
    ("kh", "Khmer"),
    ("ko", "Korean"),
    ("la", "Lao"),
    ("ma", "Madurese"),
    ("mg", "Malagasy"),
    ("ms", "Malay"),
    ("man", "Mandarin"),
    ("mi", "Maori"),
    ("mo", "Mongolian"),
    ("ne", "Nepali"),
    ("pal", "Palauan"),
    ("pas", "Pashtu"),
    ("pi", "Pitkern"),
    ("pt", "Portugese"),
    ("pa", "Punjabi"),
    ("ru", "Russian"),
    ("sm", "Samoan"),
    ("si", "Sinhala"),
    ("es", "Spanish"),
    ("su", "Sundanese"),
    ("tl", "Tagalog"),
    ("tai", "Taiwanese"),
    ("ta", "Tamil"),
    ("te", "Tetum"),
    ("th", "Thai"),
    ("bo", "Tibetan"),
    ("tok", "Tokelauan"),
    ("to", "Tongan"),
    ("ur", "Urdu"),
    ("vi", "Vietnamese"),
)

video_topics = (
    ("poverty", "Poverty"),
    ("indigenous", "Indigenous"),
    ("refugee", "Migrant workers"),
    ("health", "Health"),
    ("corporations", "Corporations / Privatisation"),
    ("work", "Labour"),
    ("conflict", "Conflict"),
    ("human", "Human Rights"),
    ("gender", "Gender / Sexuality"),
    ("race", "Racism"),
    ("religion", "Religion"),
    ("art", "Art / Culture"),
    ("media", "Media / Technology"),
    ("politics", "Politics"),
    ("education", "Education / Students"),
    ("biodiversity", "environment and forests"),
    ("climate", "Climate Change"),
    ("conservation", "Forests"),
    ("energy", "Energy"),
    ("environment", "Environment"),
    ("animal", "Animal Rights"),
    ("water", "Water / Food Security"),
    ("biotech", "Biotech"),
    ("civillib", "Civil Liberties"),
)

video_countries = (
    ("AQ", "Antarctica"),
    ("AU", "Australia"),
    ("BD", "Bangladesh"),
    ("BT", "Bhutan"),
    ("BU", "Bougainville"),
    ("BN", "Brunei Darussalam"),
    ("KH", "Cambodia"),
    ("CN", "China"),
    ("EG", "Egypt"),
    ("FJ", "Fiji"),
    ("PF", "French Polynesia"),
    ("GU", "Guam"),
    ("HA", "Hawaii"),
    ("HK", "Hong Kong"),
    ("IN", "India"),
    ("ID", "Indonesia"),
    ("XX", "International"),
    ("JP", "Japan"),
    ("KI", "Kiribati"),
    ("KP", "Korea, Democratic People's Republic Of"),
    ("LA", "Laos"),
    ("MY", "Malaysia"),
    ("MV", "Maldives"),
    ("MH", "Marshall Islands"),
    ("FM", "Micronesia, Federated States Of"),
    ("MN", "Mongolia"),
    ("MM", "Myanmar"),
    ("NR", "Nauru"),
    ("NP", "Nepal"),
    ("NC", "New Caledonia"),
    ("NZ", "New Zealand"),
    ("MP", "Northern Mariana Islands"),
    ("PK", "Pakistan"),
    ("PW", "Palau"),
    ("PG", "Papua New Guinea"),
    ("PH", "Philippines"),
    ("PN", "Pitcairn"),
    ("WS", "Samoa"),
    ("SG", "Singapore"),
    ("SB", "Solomon Islands"),
    ("LK", "Sri Lanka"),
    ("TW", "Taiwan"),
    ("TH", "Thailand"),
    ("TI", "Tibet"),
    ("TL", "Timor-Leste"),
    ("TK", "Tokelau"),
    ("TO", "Tonga"),
    ("TV", "Tuvalu"),
    ("VU", "Vanuatu"),
    ("VN", "Viet Nam"),
    ("WP", "West Papua"),
    ("KR", "south Korea"),
)
license_options = (
    ("Yes", "Yes"),
    ("No", "No"),
    ("Partially", "Partially"),
)
